:PROPERTIES:
:ID:       8861753a-0065-447a-8a0b-ec10cccf54f6
:END:
#+title: Gas turbine engine design

* Design considerations
** Comparison to piston engines
Gas turbines offer better power-to-weight ratios than piston engines.

** Design factors
- Speeds
- Endurance/range
- Height (cleared maximum altitude and typical operating altitude)
- Take off field length
- Noise
- Engine installation
- Legislative requirements
- Direct operating cost
- Specific fuel consumption (SFC)
- Weight
- Thrust per unit mass flow of air
- Unit cost
- Non-recurring cost
- Noise and gaseous emissions
- Maintainability

** Basic principles
See [[id:e89bfa23-2189-4341-b810-6e9802312de9][Gas turbine engine basics]]

** Civilian vs military applications
*** Civilian
Largest payload for lowest operating cost. Low noise and emissions.
Use large single stage fan followed by multistage compression and a large turbine. High bypass.
*** Military
Manueverability, frontal area, weight, speed, fuel consumption dominate. Cost less important.
Low bypass engines, often fitted with reheat.

* Basic equations

Specific fuel consumption SFC = (Fuel consumption)/(Net thrust) = (WFE)/(FN)

Thermal efficiency = (Kinetic energy available for work)/(Fuel energy input) = (W(V_J^2 - V_0^2))/(2.WFE.FHV)

Propulsive efficiency = (Useful propulsive power)/(Kinetic energy available for work) = (2.FN.V_0)/(W(V_J^2 - V_0^2))

Hence, SFC = (Consant \times Flight velocity)/(Thermal efficiency \times Propulsive efficiency) = (k.V_0)/(\eta_th \cdot \eta_prop)

* Engine architectures
** Core and propulsor
The engine can considered in two parts which can be considered relatively independant and can be tailored to suit aircraft application.
- The core
  - Convert fuel energy supplied to useful kinetic energy
  - Effectiveness determined by *thermal efficiency*
- The propulsor
  - To convert available kinetic energy to useful propulsive work
  - Effectiveness determined by *propulsive efficiency*

High *thermal efficiency* requires:
- Optimum turbine entry temperature (TET) and overall pressure ratio (OAPR)
- High isentropic efficiency
- Low secondary air system losses
- Low secondary mechanical losses
High *propulsive efficiency* requires:
- Large amount of air moving slowly
- Increases as forward speed approaches jet velocity

Improvements in *thermal efficiency* are becoming more difficult as practical limits of TET and OAPR are approached. Increasing *propulsive efficiency* requires larger propulsor systems, causing increased cost and weight.

** Effect of fan size and BPR
Constant fan size \rarr constant inlet mass flow \rarr specific thrust & propulsive efficiency constant

If TET reduced to reduced to achieve power requied for mc_p \Delta T, the core flow must increase and bypass ratio reduces. SFC increases because thermal efficiency is reduced.

If TET increases, core flow reduces and thermal efficiency increases - reducing SFC.

If fan size increases, and core remains same size, then the specific thrust reduces and propulsive efficiency increases and SFC reduces.

** Limitations on fan size
For given core size, increase in bypass ratio increases size and weight of engine, as nacelle has larger diameter. This also increases drag.

For wing-mounted engines there are issues of wing structure, wing flutter, aerodynamic interference drags, and landing gear length.

For tail-mounted engines the dominant factor is interference drag and lateral balance.

*** Twin engine aircraft
Twin engine aircraft have proportionally larger engines to cater for engine out cases at take-off. Engine placement relative to local wing chord is not usually a problem.
Engines mounted in front and below the wing cause aerodynamic interference, degrading the lift. The larger the nacelle, the greater the interference. Hence, there is a relationship between nacelle diameter and local chord for optimum performance.

*** Four engine aircraft
The outboard engine diameter to local chord is much higher, causing more interference.
Places a limitation on fan size, as it is desirable to have common engines inboard and outboard.

*** Other considerations
Considerations must be given to failure cases, for example in the case of a heavy landing causing a collapsed nose gear. There must be clearance given so that the nacelle does not impact the runway and potentially cause a fire.

** LP turbines and bypass ratio
Increasing fan diameter increases fan work, placing more demands on LP turbine.

*** Efficiency
- Larger fans have lower rotational speed as fan roations speed is limited by the linear tip [[id:0e42ba60-18fc-4f17-a227-cf7cab76ca51][Mach number]]
- A turbine stage efficiency is a function of its loading \Delta H/U^2
  - The lower the loading the higher the efficiency
  - \Delta H is the work extracted, the lower the work the higher the efficiency
  - U is the mean blade speed, the greater the rotational speed and the larger the radius the higher the efficiency
- Hence, the higher the BPR, the smaller the LP turbine mass flow
  - So, to maintain stage efficiency more stages are required to share the work or a larger diameter to increase the mean blade speed

*** Geared fans
- Despite core sizes reducing due to higher TET capabilities, fan diameters have still increased
  - This leads to mismatch between fan and driving turbine optimum speeds
  - Can be resolved by using a gearbox
- Incorporating a gearbox into the LP system can increase turbine speed relative to the fan
  - Reduces number of stages
- Issue is the cost, weight, and efficiency of a gearbox vs. a larger LP turbine
- Crossover point is a BPR of approx 12-14
- The problem is for larger engines, where the gearbox could be greater than 60000hp

** Open rotor
- The logic of increasing BPR leads to the open rotor, a modern turboprop
- Relatively conventional core, driving large contra-rotating fans through a gearbox
- Propulsive efficiency would be very high
- These are suitable for medium range aircraft
  - Blade length & gearbox power requirements too high for long range aircraft
- The issues are blade certification and noise
- However, most fuel is used on missions of range up to 1500 nautical miles, which is where open rotor could play signficiant part in reducing total global fuel usage
- Two configurations:
  - Pusher (rotors at rear of engine)
  - Tractor (rotors at front of engine)

** Engine offtakes
*** Conventional engine offtakes
In conventional aircraft and engine arrangements, the secondary power sources are generally mechanical and pressurised air. In both 2 or 3 spool architectures, the mechanical power is taken directly from HP system from radial mechanical drive to an accessory gearbox on the outside of the engine. This drives electrical generators and hydraulic pumps for the plane's systems. In addition, the gearbox also drives the electrical generator and oil and fuel pumps needed by the engine itself.
The pressurised air is ducted from the core of the engine at the appropriate pressure, cooled, and introduced into the passenger cabin.
The engine is started by rotating the HP system through the radial drive from an air turbine starter mounted on the auxillary gearbox. The pressurised air for the starter is provided from the aircraft auxillary power unit, or a ground support system.

A compressor will be designed with adequate surge margin between the working line and the surge line. Frequently, variable stator vanes and air bleed valves are used, especially at low flows where the surge margin tends to be lower. The cabin pressurised air taken off the compressor acts in a similar manner to a handling bleed and tends to lower the compressor's working line, improving stability.

**** HP compressor characteristics - conventional
Extracting mechanical power from the HP spool of an engine causes the working line to rise, to produce the additional power more energy must be supplied to the engine by increasing the fuel flow and raising the TET. As the turbine capacity is constant to maintain the same mass flow, the pressure ratio must increase, raising the working line. This is not usually a problem as the amount of power taken is relatively small in comparison with the total engine power.

*** More electric offtakes
As the aircraft is using electrical power for more systems, the generator has to be significantly larger, requiring more power from the engine to drive. Consequently, the mechanical requirements for a more electrical aeroplane can be a signficant proportion of total engine power. Especially when the engine power is low as in the aircraft descent case. Uniquely, for a 3 spool engine it is possible to take power off the IP system which lower the surges line on the IP compressor resulting in a reduced fuel burn as bleed values are closed. Starting time is restored by optimising the IP compressor vane schedule.

**** IP compressor characteristics - compressors in series
The IP system is more tolerant of power being taken. The fuel flow is increased to provide the additonal energy as before. Because the power is being taken off the IP system to drive the generators, the compressor is not capable of producing the required pressure ratio and the working line falls, moving the IP away from surge.

**** HP compressor characteristics - compressors in series
As the HP turbine capacity is constant, the HP system makes up this pressure ratio deficit by moving to a higher operating point. The working line does not rise, as the mass flow, temperature, and pressure are maintained in the correct relationship. This provides significant benefits. During flight idle, in descent, and on approach, the IP bleed valves are not required to open. This saves fuel, on a short range missing this can be significant. If the bleed values are closed on approach, this eliminates forward-arc noise making the aircraft quieter. The IP offtake utilises the unique architecture of the 3 spool engine. It provides significant benefits for the aircraft, the environment, and the airline by improved fuel burn, lower noise, and reduced maintenance costs.

* Summary
- Engines are designed to be the optimum for the mission they are required to perform
- Engine architectures have changed considerable in response to changing requirement and advances in technology
- The trends have been to reduce fuel consumption by:
  - High thermal efficiency
    - High OPR and TET
    - High component efficiency
    - Low losses
  - High propulsive efficiency
    - Low specific thrust
- There are a number of potential variations in engine architectures to achieve further reductions in fuel burn
- Customer requirements, legislation, company design style, and available technology all contribute to the engine's architecture
