:PROPERTIES:
:ID:       3a3559d8-9c54-432f-a8e1-769911e2ccaa
:END:
#+title: Thrust reversers

* Operation
- Reverse thrust is achieved creating a retarding force by directing air jets forwards or increasing drag.
- Requires the engine to increase power.
- Used to reduce landing distance.
- Aircraft are certified to land within a specified distance without the use of reversers.
- However they are provide assurance on wet or icy runways.
- Use has become less with the introduction of carbon brakes which are more effective than previous.

** Typical standard operating procedure
- Idle thrust reverse must be deployed on every landing.
- Maximum thrust reverse thrust must be used for all landing where the landing distance performance calculation indicates that without thrust reverse and with a contaminated runway there is insufficient runway available to land.
- For environmental friendly reasons pilots should not use greater than idle thrust reverser unless operationally required for example:
  - For brake cooling/ temperature requirement
  - Air traffic requests Braking to Vacate (BTV) the runway at a position earlier than the wet braking line.

* Types
** Clamshell
- Quite common for small engines
- Requires a single final nozzle as opposed to separate jets
- External drag due to ‘Stangs’ containing actuating mechanism
- Difficult efflux pattern management especially on rear engine ‘T’ tail aircraft
- Largely superseded by pivoting doors.
** Cascade
- A clean external profile
- Held in position by three locks, two locks on command, one lock on command with ‘weight on wheels’
- Deployed by releasing the locks and translating on ball screws either electrically, pneumatically or hydraulically
- Reverse thrust achieved by air turning
- Can be used to reverse the aircraft from the gate, but not a normal practice.
** Pivoting door
- For mixed engines they have the advantage of a clean external profile compared to clamshell reversers.
- For underwing applications each door is held in the stowed position by three locks, two locks on command, one lock on command with ‘weight on wheels’
- Deployed by releasing the locks and using the bypass air pressure.
- Reverse thrust achieved by a combination or increased drag and air turning
- As drag is a major component retarding force diminishes with speed
