:PROPERTIES:
:ID:       626f17bb-0f09-4335-81ef-03cfd2f4eb87
:END:
#+title: Trailing vortices

- Rotate inwards. Clockwise on the right wing-tip and anticlockwise on the left.
- Wing-tip vorticies are long and so dictate separation distance of aeroplanes.
  - And hence landing frequency at airport
- Induce significant drag

* Wing-tip vortex creation
Lift created by the pressure difference between lower and upper aerofoil surfaces.
For a 3D finite wing flow is induced around the wing tip, from the lower to upper surface by this pressure difference.
This forms the wing-tip vortex.

* Downwash and drag
For a 2D wing, there are no trailing vortices. Lift is perpendicular to U_\infin.

In a 3D wing, wing-tip vortices are present and cause a downwash velocity.
Effective U_\infin is changed, U_\infin,eff: angled toward chord line.
Difference between U_\infin and U_\infin,eff vectors is downwash velocity.
Difference between U_\infin and U_\infin,eff angles is downwash angle.

Lift is not perpendicular to the effective free-stream, U_\infin,eff.
Components of lift L_up and D_i. Where L_up is vertical lift and D_i is induced drag.
Induced drag D_i is orthogonal to downwash velocity.
Angle between component is downwash angle \alpha_d.

* Formulae
** Downwash velocity
w = U_\infin,eff - U_\infin
** Downwash angle
\alpha_d = tan^-1(w/U_\infin)
Where w is downwash velocity.
** Induced drag
C_D,i = (C^2_L)/(\pi AR)
Where C_L is the lift coefficient (see: [[id:12e0bef5-93ff-41f3-9ba2-22bb42b782a2][Aerofoil coefficients]]).
** Total drag coefficient
C_D = C_D0 + (C^2_L)/(\pi AR)
Where C_D0 is the 2D drag (see: [[id:12e0bef5-93ff-41f3-9ba2-22bb42b782a2][Aerofoil coefficients]]).

