:PROPERTIES:
:ID:       1ee6f188-9cba-4870-8266-626fe7628cd6
:END:
#+title: Kutta-Joukowski theorum

To simplify deriving \Gamma, a rotating circular cylinder is considered, as in the [[id:9f18fe30-abaa-4d2d-af1f-5697f794c3b4][Magnus effect]], which rotates with speed K = \Gamma / (2\pi) and which has a radius a. (See: [[id:54e6fb44-f9a9-4515-920b-9c3ada22d266][Circulation]]).
U_0, p_\infin are velocity and pressure in the freestream. V, p are velocity and pressure near the cylinder surface. We calculate the pressure distribution using the [[id:2aaabf68-4c99-46dd-8358-73edb77da674][Bernoulli equation]].
p_\infin + (\rho/2)U_0^2 = p + (\rho/2)|V|^2
Velocity |V| can be calculated from [[id:2ff01540-28bc-48a4-a292-c9013669295b][Streamfunction]] \psi.

* Derivation
Streamfunction for a rotating circular cylinder:
\psi = U_0 r sin\theta (1 - a^2/r^2) + K ln(r/a)
From streamfunction of stationary cylinder and irrotational vortex.

Velocities for a rotating circular cylinder:
Radial velocity
v_r = (1/r) \cdot (\partial \psi)/(\partial \theta) = U_0 cos\theta (1- a^2/r^2)
Tangential velocity
v_\theta = -(\partial \psi)/(\partial r) = -U_0 sin\theta (1 + a^2/r^2) - K/r
At surface:
v_r = 0, v_\theta = -(2U_0 sin\theta + K/a)

Hence, at cylinder surface |V| = -(2U_0 sin\theta + K/a)
Substituting into Bernoulli,
p_\infin + (\rho/2)U_0^2 = p + (\rho/2)U_0^2 (2 sin\theta + K/(aU_0))^2
Hence, integrating over the circular area of the cylinder,
L = \int^2\pi_0 dL
Where dL = dF_up = -(PdA)sin\theta
Where dA = ad\theta
Hence
L = -\int^2\pi_0 (p-p_\infin)a sin\theta d\theta
L = -(\rho/2)U_0^2 a\int^2\pi_0 (1-(2 sin\theta + K/(aU_0))^2)sin\theta d\theta
L = \rho U_0 (2\pi K) = \rho U_0 \Gamma

Therefore

* Result
L = \rho U_\infin \Gamma

Hence, increasing circulation \Gamma = 2\pi K increases lift.

