:PROPERTIES:
:ID:       39a7c24d-df84-493f-a8e1-536b65b66981
:END:
#+title: Low bypass ratio engines
* The turbofan
- Propulsive effiency of an engine can be increased by ducting some of the intake air around the core
  - Called a bypass
- The bypass ratio (BPR) is the ratio of bypass flow to core flow
- The turbofan retain the high thermal efficiency and low gas generator weight of a high turbine entry temperature turbojet, but with high propulsive efficiency that the turbojet gives only at low turbine entry temperature
- Engines with same total flow will have the same propulsive efficiency irrespective of BPR
- BPR limited by turbine entry temperature capability that was required at takeoff, in addition to keeping nacelle size small to reduce aero drag
- Bypass air provides annular ring of cooler air around hot core, final jet has lower mixed mean velocity which significantly reduces noise
- Disadvantage that intake area required increases volume and diameter of engine relative to simple turbojet

* Mass flow, momentum, and energy
** Low flow high velocity vs. high flow low velocity
Small mass w, high velocity V
Momentum (thrust): w.V
Energy: w.V^2/2

Large mass W, low velocity v
Momentum: W.v
Energy: W.v^2/2

Hence, if w.V = W.v, then energy required for the smaller mass flow is greater.
** Specific thrust
Specific thrust, FN/W, is the ratio of the thrust generated to the total airflow.
The higher the airflow at a given thrust, the lower the specific thrust and hence the higher the propulsive efficiency (as the jet velocity is lower).

* Low bypass ratio engines
Core of the engine is usually a HP multi-stage compressor, driven by a single stage turbine.
The LP system is a multi-stage axial compressor driven by a single or two stage tubine.

** Military applications
Military low bypass ratio turbofans are configurations where a small frontal area is required. But have an increased fuel consumption over turbojets for range and endurance. These are frequently fitted with afterburners to give increased thrust when commanded by the pilot.
