:PROPERTIES:
:ID:       872886f1-7923-45c2-a3d2-9dfdf57e6bb1
:END:
#+title: Brayton cycle

Ideal power cycle of a gas turbine engine.
The efficiency of this is the [[id:4b8ea1b7-bc32-4987-93d6-bd9b296d24ca][Cycle efficiency]].

* Cycle numbers

1 -> Compressor -> 2 -> Combusion chamber -> 3 -> Turbine -> 4 -> Heat exchanger (atmosphere) -> 1

* Diagrams
** Description of cycle p-V diagram
Across the compressor, there is an ideal ([[id:0cff770f-30ce-42f8-aa7a-1199c88fdb56][Isentropic]]) compression:
p_2/p_1 = (v_1/v_2)^\gamma

Across the combustion chamber, the volume increases at constant pressure before it enters the turbine.

Across the turbine, there is an ideal ([[id:0cff770f-30ce-42f8-aa7a-1199c88fdb56][Isentropic]]) expansion:
p_3/p_4 = (v_4/v_3)^\gamma

** Description of the T-s diagram
Area inside diagram represents net work output per unit mass, w_net.

Across the compressor, there is ideal compression. Temperature increased at constant [[id:bb975d06-10f8-41d2-b7cc-b0cb3af6393a][Entropy]].
T_2/T_1 = (p_2/p_1)^((\gamma-1)/\gamma)

Across the combusion chamber, heat addition at constant p with increasing entropy s.

Across turbine, constant entropy expansion with decreasing temperature.
T_3/T_4 = (p_3/p_4)^((\gamma-1)/\gamma)
* Increasing pressure ratio
Increase pressure increase over the compressor and pressure decrease over the turbine.
More heat is added as a result in the compressor. However the same amount of the heat is removed by the atmospheric heat exchanger, therefore a greater proportion of heat is being turned into work. Therefore greater [[id:4b8ea1b7-bc32-4987-93d6-bd9b296d24ca][Cycle efficiency]].

However, this causes higher turbine entry temperature (TET) which is limited by the turbine inlet temperature.
Therefore, to not exceed the maximum inlet temperature the heat addition by the combustion chamber is limited. The cycle then has a higher efficiency but less work output per kg of working fluid.
A higher mass flow rate needs to be put through the engine to compensate.

* Realistic cycle
In reality, the compression and expansion in the compressor and turbine are no isentropic processes, and therefore entry is added in both cases - increasing the exit temperatures.
This means a higher pressure increase in the compressor meaning more work is required to compress the air, and a lower pressure drop is created in the turbine resulting in lower work output.

The isentropic efficiency of the [[id:102568d2-a06b-416f-9037-1ce6c86164db][Turbine]] and [[id:841a1d13-5409-4bb8-bd35-5cbdcd423b6a][Compressor]] can therefore be defined in relation to the ideal and actual work over each.

* Multiple stages
Can consider change in pressure across each stage or across whole compressor.
Hence isentropic [[id:841a1d13-5409-4bb8-bd35-5cbdcd423b6a][Compressor efficiency]] can be defined by:
Whole compressor temperature differences \Delta T_is,whole and \Delta T_whole
Individual stages \Delta T_is,1 , \Delta T_is,2 , \Delta T_is,3 , ... and \Delta T_1 , \Delta T_2 , \Delta T_3 , ... and calculating efficiency for each stage

However, \Delta T_is,whole \neq \Sigma \Delta T_is,i
Which presents a problem
