:PROPERTIES:
:ID:       28e3da39-b63d-4b08-8636-e3c9f23146c0
:END:
#+title: Aero reciprocating engines

* Features
Ignition:
- Two engine-driven magnetos supplying two independant spark plug systems
Fuel system:
- Can be normally aspirated, fuel injection, or supercharged
- Aviation rated fuel
Cooling:
- Typically air-cooled
There is a provision for carburettor anti-icing

* Engine types
- Inline
- Inverted inline
- Rotary
- Horizontally opposed
- H inline
- V inline
- Inverted V inline
- Radial
  - Single row
  - Two rows

* Engine key parts
- Exhaust manifold
- Inlet manifold
- Air inlet
- Carburettor
  - Throttle
  - Venturi
  - Jet
  - Air intake
  - Float chamber

** Carburettor anti-icing
At high altitude and in foggy/cloudy conditions, ice can accumulate in the carburettor, impeding airflow.
To combat this, a valve is used which can be used to close off the air supply from the main air inlet, and instead feed air into the carburettor which has been passed over the hot exhaust manifold. This hot air aids in de-icing the carburettor. This valve can be fully/open closed or partially open.
