:PROPERTIES:
:ID:       257e9f3a-83d9-4361-a517-68adc880d7ee
:END:
#+title: Downwash

For a 2D wing, there are no [[id:626f17bb-0f09-4335-81ef-03cfd2f4eb87][Trailing vortices]]. [[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]] is perpendicular to freestream velocity U_\infin.

In a 3D wing, wing-tip vortices are present and cause a downwash velocity w behind and in front of wing.
Effective U_\infin is changed, U_\infin,eff: angled toward chord line.
Difference between U_\infin and U_\infin,eff vectors is downwash velocity.
Difference between U_\infin and U_\infin,eff angles is downwash angle.

Lift is not perpendicular to the effective free-stream, U_\infin,eff.
Components of lift L_up and D_i. Where L_up is vertical lift and D_i is induced drag.
Induced drag D_i is orthogonal to downwash velocity.
Angle between component is downwash angle \alpha_d.

** Formulae
*** Downwash velocity
w = U_\infin,eff - U_\infin
*** Downwash angle
\alpha_d = tan^-1(w/U_\infin)
Where w is downwash velocity.
*** Induced drag
C_D,i = (C^2_L)/(\pi AR)
Where C_L is the lift coefficient (see: [[id:12e0bef5-93ff-41f3-9ba2-22bb42b782a2][Aerofoil coefficients]]).
*** Total drag coefficient
C_D = C_D0 + (C^2_L)/(\pi AR)
Where C_D0 is the 2D drag (see: [[id:12e0bef5-93ff-41f3-9ba2-22bb42b782a2][Aerofoil coefficients]]).

** Kutta-Joukowski
(see: [[id:1ee6f188-9cba-4870-8266-626fe7628cd6][Kutta-Joukowski theorum]])

L = \rho U_\infin \Gamma
Where for 2D wings, L is orthogonal to U_\infin

3D wings work the same way except L_up is perpendicular to U_\infin.
L_up = \rho U_\infin \Gamma

Induced drag D_i is perpendicular to w. Using Kutta-Joukowski:
D_i = \rho w \Gamma
