:PROPERTIES:
:ID:       2d30ca07-48dc-478b-95b8-8d0a207f779f
:END:
#+title: Theoretical pitching moment coefficient

* Derivation
The [[id:5a271757-2d3d-4df6-9e53-6bd6f28e8081][Inviscid flow]] theory predicts no drag over a 2D aerofoil. Therefore, only [[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]] contributes to the pitching moment.

Let us take the moment about the leading edge (most common):

Using the lift calculated from integrating [[id:c0edfc27-d11a-44e4-bf55-091b7e5fd3f3][Circulation distribution]] over the chord and applying [[id:1ee6f188-9cba-4870-8266-626fe7628cd6][Kutta-Joukowski theorum]], as in [[id:f58d0440-a6c0-4713-b070-bc20f75c206c][Theoretical lift coefficient]]:
M = \rho U_0 \int_0^c 2U_0 sin(\alpha) \cdot ((c/x) - 1)xdx
Where x is distance to the leading edge.

Pitching moment coefficient:
C_M = M/(0.5\rho U_0^2 c^2) = 4sin(\alpha) \int_0^c ((c/x) - 1) \cdot (x/c) dx

Substituting variables:
\eta = x/c
((c/x) - 1) \cdot (x/c) = \eta ((1/\eta) - 1) = (\eta - \eta^2)^0.5

Hence:
C_M = 4sin(\alpha) \int_0^1 (\eta - \eta^2)^0.5 d\eta
C_M = 4sin(\alpha) \cdot (\pi/8) = (\pi/2)sin(\alpha)

* Small angle
Hence for small angles as is assumed in [[id:2b5b47ae-cc62-4cae-8895-7d444a9511e2][Thin aerofoil theory]]:
C_M = (\pi/2)\alpha

** Comparison to lift coefficient
Therefore, comparing to [[id:f58d0440-a6c0-4713-b070-bc20f75c206c][Theoretical lift coefficient]]:
C_M = C_L/4
Or
C_L = 4C_M

Therefore, if we want to replace [[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]] over the whole surface with equivalent force L, where does L act?
We denote by d the distance of the lift action point from the leading edge.
Then:
C_M = (Ld)/(0.5\rho U_0^2 c^2) = (d/c) \cdot C_L = C_L/4

Hence:
d = c/4

Lift acts at the quarter-chord point for symmetrical [[id:2b5b47ae-cc62-4cae-8895-7d444a9511e2][Thin flat plate aerofoil]].
This is shown only for a thin flat plate, but it is a good approximation for other thin aerofoils.
