:PROPERTIES:
:ID:       9dc87607-4812-4d90-b9a4-047dd32f15d4
:END:
#+title: Modified equation analysis

* Truncation error
(see also: [[id:e68eade6-677d-43ec-960e-dac6286511d4][Numerical errors]])
** Steady flow
Trunctation error is normally ignored in CFD.
Using backwards [[id:7b412b3c-ecce-47ff-a186-ef2fb10cf387][Finite differences]] method of discretization, we can obtain an equation:
((\partial\phi)/(\partial x))|_P = (\phi_P - \phi_W)/(\Delta x) + HOT(\Delta x^2)
Where we want to solve for:
u \cdot (\partial\phi)/(\partial x) = 0
Hence ignoring higher order terms (HOT):
u \cdot (\phi_P - \phi_W)/(\Delta x) = 0

We want to know what effect leaving out HOT has.

The exact representation: u \cdot ((\phi_P - \phi_W)/(\Delta x) + HOT(\Delta x^2)) = 0
Using a Taylor series expansion, \phi_W can be represented as:
\phi_W = \phi_P - (\Delta x)(\partial\phi/\partial x)|_P + ((\Delta x)^2/(2!))\cdot(\partial^2 \phi/\partial x^2)|_P - ((\Delta x)^3/(3!))\cdot(\partial^3 \phi/\partial x^3)|_P + HOT

Hence,
u(\partial \phi/\partial x) = C_0(\partial^2 \phi/\partial x^2) + C_1(\partial^3 \phi/\partial x^3) + HOT
is what the algebraic equation is representing.

So, by ignoring HOT we think we are solving
u(\partial \phi/\partial x) = 0
but in reality we are solving
u(\partial \phi/\partial x) = C_0(\partial^2 \phi/\partial x^2) + C_1(\partial^3 \phi/\partial x^3)

** Physical effect of truncation error
*** Dissipation
Therefore, C_0(\partial^2 \phi/\partial x^2) leads to a "smearing" of the solution. Contains a second derivative, as the viscosity terms do in the [[id:917a4eb2-c4c0-4bbf-83d8-ed65ccef18f2][Navier-Stokes equations]], and hence causes a damping effect on unsteadiness.

For example, a wave moving at velocity u and amplitude A_1 will travel distance \Delta x in time \Delta t. Dissipation will not affect the distance travelled of the wave from peak to peak, but will have flattened the wave, causing the waveform to spread with A_2 < A_1.

Dissipation provides stability to the solution.
*** Dispersion
And C_1(\partial^3 \phi/\partial x^3) causes point-wise oscillations in the solution.

Using the same example of a wave, dispersion gives spurious oscillations and a phase error.
(i.e. \Delta x < u\Delta t)

Dispersion causes instability.

** Unsteady flow
We can carry out similar procedure for unsteady convection:
We think we are solving this:
(\partial\phi/\partial t) + u(\partial\phi/\partial x) = 0

But in reality we are solving:
(\partial\phi/\partial t) + u(\partial\phi/) = C_0(\partial^2 \phi/\partial x^2) + C_1(\partial^3 \phi/\partial x^3)

Hence
C_0 = (u\Delta x \cdot (1-((u\Delta t)/(\Delta x))))/2
C_1 = (u(\Delta x)^2 \cdot (((3u\Delta t)/(\Delta x)) - 2((u\Delta t)/(\Delta x))^2 - 1))/6

Both terms contain (u \Delta t)/(\Delta x)
This is known as the [[id:749b6fab-dcdb-4002-a20c-27ec3eefe53a][Courant number]]. Higher Courant number signifies higher instability.
