:PROPERTIES:
:ID:       5ebe9122-1ae2-42c8-bab1-64150e5a8e77
:END:
#+title: Sources and sinks

m is the strength of the source/sink.
Velocity from a source/sink can be represented by the [[id:2ff01540-28bc-48a4-a292-c9013669295b][Streamfunction]].

* Source
Fluid velocities go radially outwards from a point (m>0).

** Effects of a source
Sources move the streamlines of uniform flow, like an obstacle. As it is [[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][Irrotational flow]], we can superpose velocities or streamfunctions.
By superposing uniform flow and a source, we can create the flow around a half-body / Rankine body with the stagnation point in the upwind location. The thickness t of the half-body depends on source strength m. We disregard the "flow" inside the body, the inside flow has no physical signficance when we want to study irrotational flow around an object.

Streamfunction around the half-body:
\psi = U_0 y + mtan^-1 (y/x)
See: [[id:2ff01540-28bc-48a4-a292-c9013669295b][Streamfunction]]

Or in cylindrical coordinates:
\psi = U_0 r sin\theta + m\theta

* Sink
Fluid velocities go radially inwards towards a point (m<0)

** Effects of a sink
Sinks have the opposite effects of a source. When combined with uniform flow, they create the flow around a half-body with the stagnation point in the downwind location.

* Closed bodies
Closed bodies are formed by combining sources and sinks with uniform flow.
Distance and strength of the sources/sinks determines the shape that is formed. Can create a *symmetric* aerofoil of any shape. Sources and sinks do not create [[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]] however, for that an [[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][irrotational]] vortex is required to create [[id:54e6fb44-f9a9-4515-920b-9c3ada22d266][Circulation]].

* Ground effect
** Method of images
Make the wall streamlined by "mirroring" every basic flow element by another element of the same type on the other side of the wall which has an opposite sign. In this way, walls can be created using sources, sinks, and vorticies.
