:PROPERTIES:
:ID:       626f17bb-0f09-4335-81ef-03cfd2f4eb87
:END:
#+title: Trailing vortices

- Rotate inwards: clockwise on the right wing-tip and anticlockwise on the left
- Wing-tip vorticies are long and so dictate separation distance of aeroplanes
  - And hence landing frequency at airport
- Induce significant drag

* Realistic picture
- Spanwise vorticies can be found around every small spanwise section of a wing
- The strength in each spanwise direction depends on spanwise variation of lift
- Here infinite (2D) vorticies are considered
- In reality each spanwise vortex is semi-infinite^\dagger and the [[id:9bfd0909-1c43-48d0-84ed-1c179add56d7][Biot-Savart theorem]] is needed to calculate velocity

\dagger The spanwise vortex is in reality finite, it extends until the vorticies at the beginning of flight. But, it is assumed that the initial vorticies are very far away.

* Wing-tip vortex creation
[[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]] is created by [[id:1ee6f188-9cba-4870-8266-626fe7628cd6][Kutta-Joukowski]] [[id:54e6fb44-f9a9-4515-920b-9c3ada22d266][Circulation]] caused by the bound vortex along the chord. This is a result of the pressure difference between lower and upper aerofoil surfaces. For a 3D finite wing flow is induced around the wing tip, from the lower to upper surface by this pressure difference. This forms the wing-tip vortex.
Wing-tip vorticies have the same [[id:54e6fb44-f9a9-4515-920b-9c3ada22d266][Circulation]] \Gamma as the bound vortex.

** Variation of circulation
[[id:54e6fb44-f9a9-4515-920b-9c3ada22d266][Circulation]] varies over the chord, e.g. for [[id:2b5b47ae-cc62-4cae-8895-7d444a9511e2][flat plate aerofoil]]
\gamma(x) = 2U_0 sin(\alpha) \cdot ((c/x) - 1)
Circulation also varies over the span, z, of a 3D aerofoil.
Local section lift:
l(z) = \rho U_0 \Gamma(z)dz
Hence, total lift of the wing of total span 2s:
L = \int_-s^s \rho U_0 \Gamma dz

*** Elliptic loading
For elliptic (sometimes called semi-elliptic): \Gamma = \Gamma_0 \cdot (1 - (z/s)^2)
Where s is the major axis and \Gamma_0 is minor axis (\Gamma at z=0, at maximum).
From [[id:1ee6f188-9cba-4870-8266-626fe7628cd6][Kutta-Joukowski theorum]]:
L = \int_-s^s \rho U_0 \Gamma dz = \int_-s^s \rho U_0 \Gamma_0 (1 - (z/s)^2) dz
Substitute variables:
\eta = z/s
d\eta = s^-1 dz -> dz = sd\eta
z = -s -> \eta = -1
z = s -> \eta = 1

Hence
L = \rho U_0 \Gamma_0 s \int_-1^1 (1 - \eta^2)d\eta = \rho U_0 \Gamma_0 s (\pi/2)
C_L = L/(\rho U_0^2 A) = (\rho U_0 \Gamma_0 s (\pi/2))/(0.5\rho U_0^2 c \cdot (2s))
C_L = (\Gamma_0 \pi)/(2U_0 c)

Using aspect ratio AR = (2s)/c => c = (2s)/(AR)

Therefore
C_L = (\pi\Gamma_0 \cdot AR)/(4s)

* Downwash
Wingtip vorticities create a [[id:257e9f3a-83d9-4361-a517-68adc880d7ee][Downwash]] where the effective freestream velocity differs from the actual freestream velocity by a downwash angle.
