:PROPERTIES:
:ID:       c6f633a5-77b8-4196-ac15-7b8641ab386e
:END:
#+title: Turbojets & low bypass engines

In a turbojet the main airflow is undivided as it passes through engine.

* Early designs
** Early turbojets
*** Centrifugal compressors
Single spool turbojets, mostly with centrifugal compressors, can combustors, and a single stage turbine.
Original Whittle engines had reverse flow combustors, to keep compressor to turbine shaft short to avoid whirling. This created aerodynamic losses and made combustors difficult to manufacture.
A straight-through design was made possible by a third bearing with an articulating shaft. Axial compressors were not developed sufficiently at the time to provide a reliable system.
Centrifugal compressors are limited to approx 4:1 pressure ratio, even modern ones.
Early turbojets were used for military applications.

*** Axial compressors
Axial compressors can develop higher pressure ratios, leading to lower fuel consumption and smaller frontal area. Can increase pressure ratio either by increasing number of stages, or increasing pressure rise per stage by improving blane/vane technology.
Difficult to add a large number of stages into one spool, as it becomes difficult to match front and rear stages to give acceptable handling characteristics. Solution to create two compressors in series, creating a two spool engine.

*** Turbojet two spool
Dividing compression system into two or more independent ones allows compressors to rematch at off-design conditions. Individual stages required to tolerate less incidence variation, so multistage compressors can have higher loading and hence be more compact, as fewer stages required for given pressure ratio.
Multi-spool compressor systems tend to require fewer handling aids, such as air bleeds.
Penalty for multishaft designs is increased mechanical complexity.

** Early turboprops - centrifugal compressors
First use of gas turbine engine in civilian application was as a turboprop. This was to capture propulsive effiency of a propeller for lower fuel consumption, combined with power-to-weight and smoother flight of a gas turbine.


* Turbojet efficiency and SFC
- There is an optimum temperature and pressure relationship for thermal efficiency.
- As TET (turbine entry temperature) increases the thermal efficiency increases, but propulsive efficiency reduces.
- SFC (see [[id:8861753a-0065-447a-8a0b-ec10cccf54f6][Gas turbine engine design]]) tends to increase with increases TET.
- Benefit of increasing TET is that for given thrust, lower mass flow is required allowing for smaller frontal area and lighter engine.

