:PROPERTIES:
:ID:       bd467448-61c5-4dfb-bdbb-2ea516628a0f
:END:
#+title: Meshing

* CAD model types
Spline model: defined using basis splines (B-splines)
Polygon model: defined by coordinates / mesh points
Distance function model: geometry defined by function

* Meshing types:
- [[id:2d6dd17b-3b64-4081-a9d2-d609a69055c8][Structured meshing]]
- [[id:0f369af6-dcfd-4ec5-b25e-60048e96d4bc][Unstructured meshing]]

* Designing meshes
Important to capture high gradients in flow. Therefore need refinement in high gradient regions, by using more mesh points. Important to have [[id:20e08c09-6934-401e-8f27-3375b09b314c][Mesh independence]].

* Meshing circles
- H-type grid
- O-type grid
- Butterfly grid
- Paved grid

* Meshing trade offs
- Time to mesh
- Accuracy
- Control
- Quality
- Cell count (run-time)
- Handling of complex geometry

* Moving simulations
** Moving meshes
Mesh points moved by a transformation.
** Re-meshing
New mesh is generated at each step of movement, which is computationally expensive.

* Mesh adaptation
Automatically refines mesh in high-gradient areas to capture detail.
