:PROPERTIES:
:ID:       54e6fb44-f9a9-4515-920b-9c3ada22d266
:END:
#+title: Circulation
* Lift in aerodynamic equations
A [[id:409d7757-4dbe-4b93-a6e7-38e372b9bb7b][cambered]] aerofoil has positive circulation if the velocity on the upper surface is greater than on the lower surface - creating [[id:84005369-0a9e-48a7-8c69-53bc4422377a][Lift]]. Imagine a closed curve around the aerofoil along which the velocity is known. Positive circulation implies the overall velocity around the loop is clockwise.

Circulation:
\Gamma = \oint U_II ds
Where \oint is the closed integral, integrating clockwise, and U_II indicates the velocity parallel to curve in the clockwise direction. This assumes the fluid is moving from left to right.
ds represents a curve length element.

[[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][Irrotational]] vortex induced by an aerofoil has velocity
U_\theta = -K/r
Where K is vortex strength and r is radial distance from the aerofoil.

By superimposing freestream U_\infin and U_\theta,
\Gamma = 2\pi K

The vortex creates larger velocity above than below the aerofoil, generating circulation and hence lift.

* Lift modelling for aerofoils
Hence only a vortex distribution (sheet distribution) is needed to calculate the lift of an aerofoil. One needs to integrate the vortex distribution along the mean camber line to get superposed effect of all small vortices, and then be able to use Kutta-Joukowski theorum.
