:PROPERTIES:
:ID:       4615a930-1324-46e2-a2d7-ee818ea1ae67
:END:
#+title: Velocity potential

Velocity potential is denoted by \phi and is applicable to 3D flows. It is used to solve irrotational flow problems.

In [[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][Irrotational flow]], gradient of the velocity potential \nabla\phi gives the flow velocity.
[[id:2ff01540-28bc-48a4-a292-c9013669295b][Streamfunction]] is also used to solve irrotational flow problems.

V = \nabla\phi = ((\partial \phi)/(\partial x) , (\partial \phi)/(\partial y))

Hence
u = (\partial \phi)/(\partial x)
and
v = (\partial \phi)/(\partial y)

Using the [[id:ad8a5073-fd5d-4c39-8b28-749060131385][Mass continuity equation]]:
(\partial u)/(\partial x) + (\partial v)/(\partial y) = 0

Hence
(\partial^2 \phi)/(\partial x^2) + (\partial^2 \phi)/(\partial y^2) = 0

Also written as the laplacian of \phi.
\nabla^2 \phi = 0

* Mathematical definition
** Cartesian coordinates
\nabla^2 \phi = (\partial^2 \phi)/(\partial x^2) + (\partial^2 \phi)/(\partial y^2) = 0

Where \nabla^2 is the laplacian

*** Velocities
u = (\partial \phi)/(\partial x)
v = (\partial \phi)/(\partial y)

** Cylindrical coordinates
\nabla^2 \phi = (\partial^2 \phi)/(\partial r^2) + (1/r) \cdot (\partial \phi)/(\partial r) + (1/r) \cdot (\partial^2 \phi)/(\partial \theta^2) = 0

Where \nabla^2 is the lapacian

*** Velocities
v_r = (\partial \phi)/(\partial r)
v_\theta = (1/r) \cdot (\partial \phi)/(\partial \theta)

* Boundary conditions
Solid boundaries: Zero normal derivative
Free boundaries: \phi = 0
