:PROPERTIES:
:ID:       2ff01540-28bc-48a4-a292-c9013669295b
:END:
#+title: Streamfunction

Lines of constant streamfunction \psi(x,y) are called streamlines. These are parallel to the local velocity vector, in other words fluid particles follow streamlines in steady flow. There is no flow across the streamline. The streamfunction does not apply to 3D flows.

Orthogonal to the streamlines are the equipotential lines, along which velocity potential \phi has a constant value.

The flow rate between streamlines a and b is obtained from:

Q_ab = \psi_a - \psi_b

Streamfunction is an alternative to [[id:4615a930-1324-46e2-a2d7-ee818ea1ae67][Velocity potential]] for solving [[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][Irrotational flow]].

Velocities obtained from:
u = (\partial \psi)/(\partial y)
v = -(\partial \psi)/(\partial x)

The streamfunction automatically satisfies the [[id:ad8a5073-fd5d-4c39-8b28-749060131385][Mass continuity equation]].

The irrotationality condition is:
\nabla \times V = ((\partial v)/(\partial x) - (\partial u)/(\partial y))e_z = 0

Hence:
\nabla^2 \psi = 0

* Boundary conditions
Solid boundaries: \psi = 0
Free boundaries: Zero normal derivative

* Cylindrical coordinates

v_r = (1/r) \cdot (\partial \psi)/(\partial \theta)
v_\theta = -(\partial \psi)/(\partial r)

* Uniform flow
u = U_0, v = 0
Hence:

\psi = U_0 y

* Sources and sinks
Velocity from [[id:5ebe9122-1ae2-42c8-bab1-64150e5a8e77][Sources and sinks]] in cylindrical coordinates:

v_r = m/r
v_\theta = 0
Where m>0 for a source and m<0 is a sink.

Hence -(\partial \psi)/(\partial r) = 0
Hence
\psi = \psi(\theta)
(1/r)(\partial \psi)/(\partial \theta) = m/r

Hence by integration,
\psi = m\theta for a source/sink.

Equivalently in cartesian coordinates, \psi = mtan^-1 (y/x)
Where m is the strength of the source/sink.

* Doublet
A doublet is a superposition of [[id:5ebe9122-1ae2-42c8-bab1-64150e5a8e77][a source and a sink]] where their sepratation goes to zero (a \rarr 0)
2a is the spacial separation between the source and sink.

\psi = -(\lambda sin\theta)/(r)
Where \lambda is the doublet strength.

** Streamfunction over a static cylinder
Superposing a doublet and uniform flow gives the flow over a cylinder
No flow into the cylinder, so the cylinder surface needs to be a streamline.
Hence \psi = 0 at r = a, where a is the radius of the cylinder.

Hence U_0 a sin\theta - (\lambda sin\theta)/(a) = 0
Solving for \lambda:
\lambda = U_0 a^2

Hence streamfunction becomes:
\psi = U_0 r sin\theta (1- (a^2)/(r^2))

This satisfies both the surface boundary conditional and [[id:46eacf6c-195d-4f0b-81f9-62bc6f4c2f36][irrotationality]] as \nabla^2 \psi = 0.

* Irrotational vortex
** Velocity in cylindrical coordinates
v_r = 0
v_\theta = K/r
** Streamfunction definition in cyclindrical coordinates
v_r = (1/r) \cdot (\partial \psi)/(\partial \theta)
v_\theta = -(\partial \psi)/(\partial r)
** Streamfunction
\psi = -K ln(r/a)
