:PROPERTIES:
:ID:       8ac1d8d9-9fad-42a0-ac17-ef6ea006599f
:END:
#+title: k-epsilon model

The k-\epsilon mode is a two equation [[id:341e55e9-c2df-4daf-a31e-fac9337e1638][Eddy viscosity model]].
The equations are solved for each time step and used to calculate eddy viscosity and hence [[id:e43e1cea-99a7-47c1-99c1-5741791b2461][Reynolds stress]]es.

k-turbulent kinetic energy per unity mass = 0.5(\oline{u'^2} + \oline{v'^2} + \oline{w'^2})

\epsilon-rate of viscous dissipation per unit mass = (k^{3/2})/L
Where L is representative of a turbulent length scale
(caused by work done by the smallest eddies against viscous stress)

For accurate near-wall solutions, [[id:c10a3e7e-d03c-4e1f-82cd-bcfb440f0ae8][Turbulence damping functions]] are required.

* Equations
** Transport equation for k
(\partial \oline{u}k)/(\partial x) + (\partial \oline{v} k)/(\partial y) = S \nu_T k + Diffusion term[\sigma] - Destruction term[C_1]

LHS represents advection
S\nu_T k represents production

** Transport equation for \epsilon
(\partial \oline{u} \epsilon)/(\partial x) + (\partial \oline{v} \epsilon)/(\partial y) = C_1 S \nu_T \epsilon + Diffusion term[\sigma] - Destruction term[C_2]

LHS represents advection
S\nu_T \epsilon represents production

** Eddy viscosity
(see: [[id:341e55e9-c2df-4daf-a31e-fac9337e1638][Eddy viscosity model]])

\mu_T = \rho C_\mu (k^2/\epsilon)

* Isotropic turbulence
Negligible transport of turbulence, no production, negligible diffusion.
Only destruction term remains.
